"""Change length column id user role link

Revision ID: 055006201162
Revises: 3df543234636
Create Date: 2022-10-08 16:23:18.836334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '055006201162'
down_revision = '3df543234636'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
