"""Added new fields in slot table

Revision ID: 0b04384d9f88
Revises: b99a0267ccb5
Create Date: 2022-12-18 08:55:07.722645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b04384d9f88'
down_revision = 'b99a0267ccb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
