"""Added ClientSidePermission

Revision ID: 0ee372813b1f
Revises: 4a661867d17c
Create Date: 2022-10-08 14:50:42.527747

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0ee372813b1f'
down_revision = '4a661867d17c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('psy_code')
    op.add_column('psy_role', sa.Column('code', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('psy_role', 'code')
    op.create_table('psy_code',
    sa.Column('code', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('desc', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('id', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('code'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
