"""Added primary key at user_id

Revision ID: 193da78ed860
Revises: 72c922ad3147
Create Date: 2022-12-16 19:44:25.079245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '193da78ed860'
down_revision = '72c922ad3147'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('psy_user_calendar_event_link', 'user_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('psy_user_calendar_event_link', 'user_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
