"""Added active column

Revision ID: 2abbe270779d
Revises: 4ce846c07649
Create Date: 2023-01-10 03:15:05.305055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2abbe270779d'
down_revision = '4ce846c07649'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('psy_user', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('psy_user', 'active')
    # ### end Alembic commands ###
