"""Added salut for user

Revision ID: 2e71e382970d
Revises: 8cb27f5c9d22
Create Date: 2022-12-26 08:41:57.219031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e71e382970d'
down_revision = '8cb27f5c9d22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
