"""Change to class for UserRoleLink

Revision ID: 345f8d5d8004
Revises: 0ee372813b1f
Create Date: 2022-10-08 15:01:30.220268

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '345f8d5d8004'
down_revision = '0ee372813b1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('psy_user_role_link', sa.Column('id', sa.String(length=50), nullable=False))
    op.drop_constraint('psy_user_role_link_ibfk_1', 'psy_user_role_link', type_='foreignkey')
    op.drop_constraint('psy_user_role_link_ibfk_2', 'psy_user_role_link', type_='foreignkey')
    op.drop_column('psy_user_role_link', 'role_id')
    op.drop_column('psy_user_role_link', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('psy_user_role_link', sa.Column('user_id', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('psy_user_role_link', sa.Column('role_id', mysql.VARCHAR(length=50), nullable=True))
    op.create_foreign_key('psy_user_role_link_ibfk_2', 'psy_user_role_link', 'psy_role', ['role_id'], ['id'])
    op.create_foreign_key('psy_user_role_link_ibfk_1', 'psy_user_role_link', 'psy_user', ['user_id'], ['id'])
    op.drop_column('psy_user_role_link', 'id')
    # ### end Alembic commands ###
