"""Add slot foreign key 3

Revision ID: 35d972257bd6
Revises: 56b0c601e40c
Create Date: 2022-12-18 19:38:09.429411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35d972257bd6'
down_revision = '56b0c601e40c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
