"""Add id column to user role

Revision ID: 3df543234636
Revises: ca25cf84bcaa
Create Date: 2022-10-08 16:14:46.369972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3df543234636'
down_revision = 'ca25cf84bcaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('psy_user_role_link', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('psy_user_role_link', 'id')
    # ### end Alembic commands ###
