"""Remove description  col at calendar event

Revision ID: 495035ef5621
Revises: 193da78ed860
Create Date: 2022-12-17 10:13:45.219580

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '495035ef5621'
down_revision = '193da78ed860'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('psy_calendar_event', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('psy_calendar_event', sa.Column('description', mysql.VARCHAR(length=500), nullable=True))
    # ### end Alembic commands ###
