"""Added user role link table

Revision ID: 4a661867d17c
Revises: c0d72ef4134d
Create Date: 2022-10-08 13:51:29.389435

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4a661867d17c'
down_revision = 'c0d72ef4134d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('psy_user_roles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('psy_user_roles',
    sa.Column('id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('role_id', mysql.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['psy_role.id'], name='psy_user_roles_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['psy_user.id'], name='psy_user_roles_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
