"""UserRoleLink add foreign key column2

Revision ID: 628620f3d891
Revises: c92e695aef42
Create Date: 2022-10-08 15:05:14.548582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '628620f3d891'
down_revision = 'c92e695aef42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
