"""Added revision to user2

Revision ID: 64c0c9a48789
Revises: 8809caae1c85
Create Date: 2022-12-26 09:06:11.648100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64c0c9a48789'
down_revision = '8809caae1c85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('psy_user', sa.Column('revision', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('psy_user', 'revision')
    # ### end Alembic commands ###
