"""Add slot foreign key 4

Revision ID: 656ec5ca2661
Revises: 35d972257bd6
Create Date: 2022-12-18 19:41:35.303915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '656ec5ca2661'
down_revision = '35d972257bd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
