"""Create slot table

Revision ID: 7064dc1fd518
Revises: 0b04384d9f88
Create Date: 2022-12-18 08:59:15.957726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7064dc1fd518'
down_revision = '0b04384d9f88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
