"""change col type to string(50)

Revision ID: 72c922ad3147
Revises: c3ffd3ca1de2
Create Date: 2022-10-13 20:00:44.972142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72c922ad3147'
down_revision = 'c3ffd3ca1de2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
