"""Remove not null constraint in user

Revision ID: 7fc3dbf73801
Revises: 2abbe270779d
Create Date: 2023-01-10 03:30:25.971647

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7fc3dbf73801'
down_revision = '2abbe270779d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('psy_user', 'lastName',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('psy_user', 'gender',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('psy_user', 'age',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('psy_user', 'profPic',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('psy_user', 'IC',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('psy_user', 'race',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('psy_user', 'mobile',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('psy_user', 'mobile',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('psy_user', 'race',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('psy_user', 'IC',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('psy_user', 'profPic',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('psy_user', 'age',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('psy_user', 'gender',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('psy_user', 'lastName',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
