"""Drop saja saja colum

Revision ID: 8cb27f5c9d22
Revises: e8bca7f54343
Create Date: 2022-12-18 19:50:32.254618

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8cb27f5c9d22'
down_revision = 'e8bca7f54343'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('psy_calendar_event', 'sajesaje')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('psy_calendar_event', sa.Column('sajesaje', mysql.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
