"""Added days column

Revision ID: a8d6ed196ec5
Revises: d2de4e1d0edc
Create Date: 2023-01-22 13:17:56.695822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8d6ed196ec5'
down_revision = 'd2de4e1d0edc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('psy_slot', sa.Column('days', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('psy_slot', 'days')
    # ### end Alembic commands ###
