"""UserRoleLink add foreign key column

Revision ID: aaf224953448
Revises: b9a2473167a7
Create Date: 2022-10-08 15:03:27.671601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaf224953448'
down_revision = 'b9a2473167a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
