"""Added title in calendar event

Revision ID: b99a0267ccb5
Revises: 495035ef5621
Create Date: 2022-12-17 19:41:06.154779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b99a0267ccb5'
down_revision = '495035ef5621'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('psy_calendar_event', sa.Column('title', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('psy_calendar_event', 'title')
    # ### end Alembic commands ###
