"""UserRoleLink add foreign key column

Revision ID: b9a2473167a7
Revises: 345f8d5d8004
Create Date: 2022-10-08 15:02:44.618975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9a2473167a7'
down_revision = '345f8d5d8004'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
