"""Added id to all table

Revision ID: c0d72ef4134d
Revises: 604740cb89b9
Create Date: 2022-10-08 13:15:47.311421

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c0d72ef4134d'
down_revision = '604740cb89b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('psy_question', sa.Column('code', sa.String(length=50), nullable=True))
    op.drop_column('psy_question', 'instruCode')
    op.add_column('psy_student', sa.Column('id', sa.String(length=50), nullable=False))
    op.drop_column('psy_student', 'studentID')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('psy_student', sa.Column('studentID', mysql.VARCHAR(length=50), nullable=False))
    op.drop_column('psy_student', 'id')
    op.add_column('psy_question', sa.Column('instruCode', mysql.VARCHAR(length=50), nullable=False))
    op.drop_column('psy_question', 'code')
    # ### end Alembic commands ###
