"""Add unique constraint for user_cal_calendar_event_id

Revision ID: c3ffd3ca1de2
Revises: 1a16bd2e1cf7
Create Date: 2022-10-13 19:57:28.771926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3ffd3ca1de2'
down_revision = '1a16bd2e1cf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'psy_user_calendar_event_link', ['calendar_event_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'psy_user_calendar_event_link', type_='unique')
    # ### end Alembic commands ###
