"""UserRoleLink add foreign key column

Revision ID: c92e695aef42
Revises: aaf224953448
Create Date: 2022-10-08 15:04:32.236228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c92e695aef42'
down_revision = 'aaf224953448'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('psy_user_role_link', sa.Column('user_id', sa.String(length=50), nullable=True))
    op.add_column('psy_user_role_link', sa.Column('role_id', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'psy_user_role_link', 'psy_role', ['role_id'], ['id'])
    op.create_foreign_key(None, 'psy_user_role_link', 'psy_user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'psy_user_role_link', type_='foreignkey')
    op.drop_constraint(None, 'psy_user_role_link', type_='foreignkey')
    op.drop_column('psy_user_role_link', 'role_id')
    op.drop_column('psy_user_role_link', 'user_id')
    # ### end Alembic commands ###
