"""Add slot foreign key

Revision ID: f23c1bef7cf0
Revises: 7064dc1fd518
Create Date: 2022-12-18 19:15:16.567139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f23c1bef7cf0'
down_revision = '7064dc1fd518'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
