"""Add slot foreign key 5

Revision ID: ff561ae85ced
Revises: 656ec5ca2661
Create Date: 2022-12-18 19:42:48.568362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff561ae85ced'
down_revision = '656ec5ca2661'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('psy_calendar_event', sa.Column('sajesaje', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('psy_calendar_event', 'sajesaje')
    # ### end Alembic commands ###
