"""change to time datatype

Revision ID: ff931d4ae4c8
Revises: 7fc3dbf73801
Create Date: 2023-01-22 11:07:34.029423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff931d4ae4c8'
down_revision = '7fc3dbf73801'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
