"""added col tr1

Revision ID: bb8e91840349
Revises: 
Create Date: 2021-02-28 19:03:50.365337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb8e91840349'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tr1', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('userID', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learner', schema=None) as batch_op:
        batch_op.drop_column('userID')
        batch_op.drop_column('tr1')

    # ### end Alembic commands ###
